### ISSUE TITLE
Fix CI Lint failing due to unchecked os.Chdir error returns

### ISSUE THREAD

**Issue by RadekCap** [RadekCap/CAPZTests#423]
## Problem

The CI Lint job is failing on the `main` branch after PR #422 was merged.

**Failed run:** https://github.com/RadekCap/CAPZTests/actions/runs/21293474301

## Error Details

The `errcheck` linter is reporting unchecked error return values from `os.Chdir`:

```
test/03_cluster_test.go:72:17: Error return value of `os.Chdir` is not checked (errcheck)
		defer os.Chdir(originalDir)
		              ^

test/04_generate_yamls_test.go:97:16: Error return value of `os.Chdir` is not checked (errcheck)
	defer os.Chdir(originalDir)
	              ^
```

## Root Cause

The deferred `os.Chdir(originalDir)` calls do not check the error return value. While these are cleanup operations that are unlikely to fail in practice, the linter requires all error returns to be checked.

## Suggested Fix

Wrap the deferred calls to explicitly handle (or ignore) the error:

```go
// Option 1: Explicitly ignore the error
defer func() { _ = os.Chdir(originalDir) }()

// Option 2: Log the error (if logging is available)
defer func() {
    if err := os.Chdir(originalDir); err != nil {
        t.Logf("Warning: failed to change back to original directory: %v", err)
    }
}()
```

## Affected Files

- `test/03_cluster_test.go:72`
- `test/04_generate_yamls_test.go:97`
